// ===========================================
// Trodat Shop - Database Seed
// ===========================================
// Populates categories and stamps from the original mock data

import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // ── Create Categories ────────────────────
  const categories = [
    { slug: 'all', name: 'All Products', series: 'all', icon: '✨' },
    { slug: 'office', name: 'Office Stamps', series: 'Printy', icon: '🏢' },
    { slug: 'heavy-duty', name: 'Heavy Duty', series: 'Professional', icon: '🏗️' },
    { slug: 'pocket', name: 'Pocket Stamps', series: 'Mobile', icon: '📱' },
    { slug: 'daters', name: 'Daters & Numerators', series: 'Professional', icon: '📅' },
    { slug: 'embossers', name: 'Embossers', series: 'Ideal', icon: '🏷️' },
    { slug: 'accessories', name: 'Accessories', series: 'Accessories', icon: '💧' },
  ];

  const categoryMap: Record<string, string> = {};
  for (const cat of categories) {
    const created = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    });
    categoryMap[cat.slug] = created.id;
  }
  console.log(`  ✅ ${categories.length} categories seeded`);

  // ── Create Stamps ────────────────────────
  const stamps = [
    {
      article: '4910',
      name: 'Trodat Printy 4910',
      series: 'printy',
      categorySlug: 'office',
      price: 850,
      size: '26 x 9 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4910',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4910%0AImpression',
      imageGallery: [],
      inkPad: '6/4910',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red', 'Grey', 'Pink'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Compact text stamp, perfect for short messages like approved, paid, or a simple signature.',
      inStock: true,
      maxLines: 2,
    },
    {
      article: '4911',
      name: 'Trodat Printy 4911',
      series: 'printy',
      categorySlug: 'office',
      price: 990,
      size: '38 x 14 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4911',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4911%0AImpression',
      imageGallery: [],
      inkPad: '6/4911',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red', 'Grey', 'White', 'Pink', 'Neon Green'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: "The Original Printy 4.0 is one of the world's smallest and lightest self-inking stamps. Climate-neutral as standard.",
      inStock: true,
      maxLines: 3,
    },
    {
      article: '4912',
      name: 'Trodat Printy 4912',
      series: 'printy',
      categorySlug: 'office',
      price: 1190,
      size: '47 x 18 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4912',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4912%0AImpression',
      imageGallery: [],
      inkPad: '6/4912',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red', 'Green', 'Orange', 'Pink'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'The most popular office stamp. Ideal for company names and addresses with up to 5 lines of text.',
      inStock: true,
      maxLines: 5,
    },
    {
      article: '4913',
      name: 'Trodat Printy 4913',
      series: 'printy',
      categorySlug: 'office',
      price: 1390,
      size: '58 x 22 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4913',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4913%0AImpression',
      imageGallery: [],
      inkPad: '6/4913',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red', 'Grey', 'White'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Larger text plate for up to 6 lines. Perfect for detailed company addresses and logos.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '4914',
      name: 'Trodat Printy 4914',
      series: 'printy',
      categorySlug: 'office',
      price: 1590,
      size: '64 x 26 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4914',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4914%0AImpression',
      imageGallery: [],
      inkPad: '6/4914',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Wide format for extended text, accommodating long company names or additional details.',
      inStock: true,
      maxLines: 7,
    },
    {
      article: '4915',
      name: 'Trodat Printy 4915',
      series: 'printy',
      categorySlug: 'office',
      price: 1890,
      size: '70 x 25 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4915',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4915%0AImpression',
      imageGallery: [],
      inkPad: '6/4915',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Extra wide and tall for large addresses, logos, and comprehensive contact details.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '4921',
      name: 'Trodat Printy 4921 Square',
      series: 'printy',
      categorySlug: 'office',
      price: 850,
      size: '12 x 12 mm',
      shape: 'square',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4921',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4921%0AImpression',
      imageGallery: [],
      inkPad: '6/4921',
      featureMci: false,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Miniature square stamp, perfect for inspection marks, initials, or small logos.',
      inStock: true,
      maxLines: 2,
    },
    {
      article: '4922',
      name: 'Trodat Printy 4922 Square',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '20 x 20 mm',
      shape: 'square',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4922',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4922%0AImpression',
      imageGallery: [],
      inkPad: '6/4922',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Compact square design, ideal for monograms or short text blocks.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4923',
      name: 'Trodat Printy 4923 Square',
      series: 'printy',
      categorySlug: 'office',
      price: 1150,
      size: '30 x 30 mm',
      shape: 'square',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4923',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4923%0AImpression',
      imageGallery: [],
      inkPad: '6/4923',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Medium square format for more detailed logos or multi-line information.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '4924',
      name: 'Trodat Printy 4924 Square',
      series: 'printy',
      categorySlug: 'office',
      price: 1490,
      size: '40 x 40 mm',
      shape: 'square',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4924',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4924%0AImpression',
      imageGallery: [],
      inkPad: '6/4924',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Large square stamp, suitable for complex logos, QR codes, or extensive text.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '46019',
      name: 'Trodat Printy 46019 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 19 mm',
      shape: 'round',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A46019',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46019%0AImpression',
      imageGallery: [],
      inkPad: '6/46019',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Small circular stamp for inspector numbers, initials, or miniature logos.',
      inStock: true,
      maxLines: 3,
    },
    {
      article: '46025',
      name: 'Trodat Printy 46025 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1050,
      size: 'Ø 25 mm',
      shape: 'round',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A46025',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46025%0AImpression',
      imageGallery: [],
      inkPad: '6/46025',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Round format for custom graphics, small monograms, and inspection marks.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '46030',
      name: 'Trodat Printy 46030 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1150,
      size: 'Ø 30 mm',
      shape: 'round',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A46030',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46030%0AImpression',
      imageGallery: [],
      inkPad: '6/46030',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Medium circular stamp, great for basic seals, logos, or personalized branding.',
      inStock: true,
      maxLines: 5,
    },
    {
      article: '46040',
      name: 'Trodat Printy 46040 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1250,
      size: 'Ø 40 mm',
      shape: 'round',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A46040',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46040%0AImpression',
      imageGallery: [],
      inkPad: '6/46040',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Classic round seal size, perfectly suited for standard company or notary seals.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '4642',
      name: 'Trodat Printy 4642 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1290,
      size: 'Ø 42 mm',
      shape: 'round',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4642',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4642%0AImpression',
      imageGallery: [],
      inkPad: '6/4642',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Red', 'Blue', 'Grey'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Circular stamp for official company seals and creative logos, extremely popular worldwide.',
      inStock: true,
      maxLines: 7,
    },
    {
      article: '46045',
      name: 'Trodat Printy 46045 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1390,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A46045',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46045%0AImpression',
      imageGallery: [],
      inkPad: '6/46045',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Larger round stamp, ideal for intricate crests, detailed logos, and bilingual seals.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '4926',
      name: 'Trodat Printy 4926',
      series: 'printy',
      categorySlug: 'office',
      price: 1850,
      size: '75 x 38 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4926',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4926%0AImpression',
      imageGallery: [],
      inkPad: '6/4926',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Large rectangular stamp accommodating up to 8 lines. Perfect for extensive tabular information.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '4927',
      name: 'Trodat Printy 4927',
      series: 'printy',
      categorySlug: 'office',
      price: 1650,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4927',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4927%0AImpression',
      imageGallery: [],
      inkPad: '6/4927',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Standard format for prominent addressing or detailed bank and accounting information.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '4928',
      name: 'Trodat Printy 4928',
      series: 'printy',
      categorySlug: 'office',
      price: 1550,
      size: '60 x 33 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4928',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4928%0AImpression',
      imageGallery: [],
      inkPad: '6/4928',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Accommodates long lines of text, commonly used for larger return addresses and instructions.',
      inStock: true,
      maxLines: 7,
    },
    {
      article: '4929',
      name: 'Trodat Printy 4929',
      series: 'printy',
      categorySlug: 'office',
      price: 1450,
      size: '50 x 30 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4929',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4929%0AImpression',
      imageGallery: [],
      inkPad: '6/4929',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Versatile size for custom messages or medium-sized addresses and department names.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5200',
      name: 'Trodat Professional 5200',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2190,
      size: '41 x 24 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5200',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5200%0AImpression',
      imageGallery: [],
      inkPad: '6/5200',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Ergonomic, reliable, and durable. The high-quality steel construction guarantees maximum stability.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5203',
      name: 'Trodat Professional 5203',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2450,
      size: '49 x 28 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5203',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5203%0AImpression',
      imageGallery: [],
      inkPad: '6/5203',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Robust design for heavy daily use, offering ample space for addresses and basic logos.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5204',
      name: 'Trodat Professional 5204',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2690,
      size: '56 x 26 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5204',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5204%0AImpression',
      imageGallery: [],
      inkPad: '6/5204',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Strongest and most reliable heavy-duty stamp for long-term industrial use. Ideal for standard business addresses.',
      inStock: true,
      maxLines: 7,
    },
    {
      article: '5206',
      name: 'Trodat Professional 5206',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2950,
      size: '56 x 33 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5206',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5206%0AImpression',
      imageGallery: [],
      inkPad: '6/5206',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Excellent for accommodating detailed texts and prominent graphic elements in heavy use environments.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '5207',
      name: 'Trodat Professional 5207',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 3250,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5207',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5207%0AImpression',
      imageGallery: [],
      inkPad: '6/5207',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Large surface area for demanding requirements, including accounting layouts or complex graphics.',
      inStock: true,
      maxLines: 9,
    },
    {
      article: '5208',
      name: 'Trodat Professional 5208',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 3600,
      size: '68 x 47 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5208',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5208%0AImpression',
      imageGallery: [],
      inkPad: '6/5208',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Extra-large format specifically designed for extensive tables, forms, or multiple signature lines.',
      inStock: true,
      maxLines: 10,
    },
    {
      article: '5211',
      name: 'Trodat Professional 5211',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 4200,
      size: '85 x 55 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5211',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5211%0AImpression',
      imageGallery: [],
      inkPad: '6/5211',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'One of the largest heavy-duty stamps, ideal for highly detailed forms, warning labels, or vast text.',
      inStock: true,
      maxLines: 12,
    },
    {
      article: '9411',
      name: 'Trodat Mobile Printy 9411',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 890,
      size: '38 x 14 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A9411',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9411%0AImpression',
      imageGallery: [],
      inkPad: '6/9411',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Silver', 'Blue', 'Red', 'Green', 'Orange', 'Yellow', 'Black', 'Pink'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'The unique one-handed operation pocket stamp. Simple, stable, and clean.',
      inStock: true,
      maxLines: 3,
    },
    {
      article: '9412',
      name: 'Trodat Mobile Printy 9412',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1050,
      size: '47 x 18 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A9412',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9412%0AImpression',
      imageGallery: [],
      inkPad: '6/9412',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Silver', 'Blue', 'Red', 'Green', 'Orange', 'Yellow', 'Black', 'Pink'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Compact travel companion providing enough space for a standard company address or signature.',
      inStock: true,
      maxLines: 5,
    },
    {
      article: '9413',
      name: 'Trodat Mobile Printy 9413',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1250,
      size: '58 x 22 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A9413',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9413%0AImpression',
      imageGallery: [],
      inkPad: '6/9413',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Silver', 'Blue', 'Red', 'Green', 'Orange', 'Yellow', 'Black', 'Pink'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'The largest Mobile Printy size for comprehensive text, logos, or full address blocks on the go.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '9425',
      name: 'Trodat Mobile Printy 9425 Square',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1100,
      size: '25 x 25 mm',
      shape: 'square',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A9425',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9425%0AImpression',
      imageGallery: [],
      inkPad: '6/9425',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Silver', 'Blue', 'Red', 'Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Square pocket stamp layout for logos, initials, and short messages in a highly portable format.',
      inStock: true,
      maxLines: 5,
    },
    {
      article: '4750',
      name: 'Trodat Printy 4750 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 1850,
      size: '41 x 24 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4750',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4750%0AImpression',
      imageGallery: [],
      inkPad: '6/4750',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet', 'Black/Red'],
      description: 'Popular everyday dater offering two text lines alongside the adjustable date field.',
      inStock: true,
      maxLines: 2,
    },
    {
      article: '4729',
      name: 'Trodat Printy 4729 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 2150,
      size: '50 x 30 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4729',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4729%0AImpression',
      imageGallery: [],
      inkPad: '6/4929',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet', 'Black/Red'],
      description: 'Mid-sized dater for custom instructions above and below the prominent date band.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4727',
      name: 'Trodat Printy 4727 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 2350,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4727',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4727%0AImpression',
      imageGallery: [],
      inkPad: '6/4927',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Black', 'Blue', 'Red'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet', 'Black/Red'],
      description: 'Larger dater format suitable for accounting, receiving, and detailed organizational workflows.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5430',
      name: 'Trodat Professional 5430 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: '41 x 24 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5430',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5430%0AImpression',
      imageGallery: [],
      inkPad: '6/50',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet', 'Black/Red'],
      description: 'Heavy-duty steel-core dater for high-volume environments requiring durability and precision.',
      inStock: true,
      maxLines: 2,
    },
    {
      article: '5440',
      name: 'Trodat Professional 5440 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 3150,
      size: '49 x 28 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5440',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5440%0AImpression',
      imageGallery: [],
      inkPad: '6/53',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet', 'Black/Red'],
      description: 'Robust and reliable dater with slightly extended space for specialized office workflows.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5460',
      name: 'Trodat Professional 5460 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 3290,
      size: '56 x 33 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5460',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5460%0AImpression',
      imageGallery: [],
      inkPad: '6/56',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet', 'Black/Red'],
      description: 'Self-inking heavy-duty dater with ample additional text area. Smooth and quiet operation.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5480',
      name: 'Trodat Professional 5480 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 4500,
      size: '68 x 47 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A5480',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5480%0AImpression',
      imageGallery: [],
      inkPad: '6/58',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ['Silver/Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet', 'Black/Red'],
      description: 'Extensive format dater suitable for large tables, comprehensive status updates, and sign-offs.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: 'Ideal Seal',
      name: 'Trodat Ideal Seal',
      series: 'ideal',
      categorySlug: 'embossers',
      price: 4500,
      size: 'Ø 41 mm',
      shape: 'round',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0AIdeal',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=Ideal%0AShadow',
      imageGallery: [],
      inkPad: 'None',
      featureMci: false,
      featureEco: false,
      featurePositioning: false,
      colors: ['Chrome', 'Black', 'Pink'],
      inkColors: ['None (Embossing)'],
      description: 'High-quality embossing press for certificates, stationary, and official documents. Leaves a crisp impression.',
      inStock: true,
    },
    {
      article: '4810',
      name: 'Trodat Printy 4810 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 850,
      size: '3.8 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4810',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4810%0AImpression',
      imageGallery: [],
      inkPad: '6/4910',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Compact dater with 3.8 mm date height. Standard format: DD.MM.YYYY.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '4820',
      name: 'Trodat Printy 4820 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 950,
      size: '4.0 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4820',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4820%0AImpression',
      imageGallery: [],
      inkPad: '6/4911',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Dater with 4 mm date height. Ideal for banking and standard document marking.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '4836',
      name: 'Trodat Printy 4836 Numerator',
      series: 'printy',
      categorySlug: 'daters',
      price: 950,
      size: '3.8 mm (6 digits)',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4836',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4836%0AImpression',
      imageGallery: [],
      inkPad: '6/4910',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: '6-digit numbering stamp with 3.8 mm character height.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '4846',
      name: 'Trodat Printy 4846 Numerator',
      series: 'printy',
      categorySlug: 'daters',
      price: 1050,
      size: '4.0 mm (6 digits)',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A4846',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4846%0AImpression',
      imageGallery: [],
      inkPad: '6/4911',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: '6-digit numerator with additional special characters. Character height 4 mm.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '48313',
      name: 'Trodat Printy 48313 Numerator',
      series: 'printy',
      categorySlug: 'daters',
      price: 1850,
      size: '3.8 mm (13 digits)',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A48313',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=48313%0AImpression',
      imageGallery: [],
      inkPad: '6/4817',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Black'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Wide 13-digit numbering stamp. Perfect for long tracking numbers. Character height 3.8 mm.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '9342',
      name: 'Trodat Micro Printy 9342',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1250,
      size: 'Ø 42 mm',
      shape: 'round',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A9342',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9342%0AImpression',
      imageGallery: [],
      inkPad: 'Built-in',
      featureMci: false,
      featureEco: false,
      featurePositioning: false,
      colors: ['Black', 'Red', 'Blue', 'Silver', 'White', 'Light Blue', 'Fuchsia', 'Light Green', 'Orange'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Simple, light, and compact round pocket stamp. Features an adhesive layer for easy mounting.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '9511',
      name: 'Trodat Pocket Printy 9511',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 950,
      size: '38 x 14 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A9511',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9511%0AImpression',
      imageGallery: [],
      inkPad: '6/9511',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Black', 'Blue', 'Red', 'Silver', 'Pink'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Extremely compact and perfectly designed pocket stamp with slide mechanism.',
      inStock: true,
      maxLines: 3,
    },
    {
      article: '7011',
      name: 'Trodat Stamp Ink 7011 (28ml)',
      series: 'accessories',
      categorySlug: 'accessories',
      price: 350,
      size: '28 ml',
      shape: 'bottle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A7011',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=7011%0AInk',
      imageGallery: [],
      inkPad: 'None',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet'],
      description: 'Water-based stamp ink suitable for all rubber and polymer text plates. Environmentally friendly.',
      inStock: true,
      maxLines: 0,
    },
    {
      article: '9052',
      name: 'Trodat Stamp Pad 9052',
      series: 'accessories',
      categorySlug: 'accessories',
      price: 550,
      size: '110 x 70 mm',
      shape: 'rectangle',
      imageMain: 'https://placehold.co/600x600/ffffff/2563EB?text=Trodat%0A9052',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9052%0APad',
      imageGallery: [],
      inkPad: 'None',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ['Black casing'],
      inkColors: ['Black', 'Blue', 'Red', 'Green', 'Violet', 'Un-inked'],
      description: 'Desktop stamp pad with new modern design. Guaranteed thousands of clean impressions.',
      inStock: true,
      maxLines: 0,
    },
  ];

  for (const stamp of stamps) {
    const { categorySlug, ...data } = stamp;
    await prisma.stamp.upsert({
      where: { article: data.article },
      update: { ...data, categoryId: categoryMap[categorySlug] },
      create: { ...data, categoryId: categoryMap[categorySlug] },
    });
  }
  console.log(`  ✅ ${stamps.length} stamps seeded`);

  // ── Create Demo Admin User ───────────────
  const hashedPassword = await bcrypt.hash('Admin123!', 12);
  await prisma.user.upsert({
    where: { email: 'admin@trodat-shop.com' },
    update: {},
    create: {
      name: 'Admin',
      email: 'admin@trodat-shop.com',
      phone: '+1234567890',
      password: hashedPassword,
      role: 'ADMIN',
    },
  });
  console.log('  ✅ Demo admin user seeded (admin@trodat-shop.com / Admin123!)');

  console.log('🎉 Seeding complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
