// ===========================================
// Trodat Shop - Database Seed
// ===========================================
// Populates categories and stamps from the original mock data

import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // ── Create Categories ────────────────────
  const categories = [
    { slug: 'all', name: 'Все товары', series: 'all', icon: '✨' },
    { slug: 'office', name: 'Серия Trodat Printy', series: 'Printy', icon: '🏢' },
    { slug: 'heavy-duty', name: 'Серия Trodat Professional', series: 'Professional', icon: '🏗️' },
    { slug: 'pocket', name: 'Мобильные штампы Trodat', series: 'Mobile', icon: '📱' },
    { slug: 'daters', name: 'Датеры и нумераторы', series: 'Professional', icon: '📅' },
    { slug: 'embossers', name: 'Серия Ideal (Рельефные печати)', series: 'Ideal', icon: '🏷️' },
    { slug: 'accessories', name: 'Штемпельные аксессуары', series: 'Accessories', icon: '💧' }
  ];

  const categoryMap: Record<string, string> = {};
  for (const cat of categories) {
    const created = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    });
    categoryMap[cat.slug] = created.id;
  }
  console.log(`  ✅ ${categories.length} categories seeded`);

  // ── Create Stamps ────────────────────────
  const stamps = [
            {
      article: '4910',
      name: 'Trodat Printy 4910',
      series: 'printy',
      categorySlug: 'office',
      price: 850,
      size: '26 x 9 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4910.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4910%0AImpression',
      imageGallery: [],
      inkPad: '6/4910',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Compact text stamp, perfect for short messages like approved, paid, or a simple signature.',
      inStock: true,
      maxLines: 2,
    },
    {
      article: '4911',
      name: 'Trodat Printy 4911',
      series: 'printy',
      categorySlug: 'office',
      price: 990,
      size: '38 x 14 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4911.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4911%0AImpression',
      imageGallery: [],
      inkPad: '6/4911',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'The Original Printy 4.0 is one of the world\'s smallest and lightest self-inking stamps. Climate-neutral as standard.',
      inStock: true,
      maxLines: 3,
    },
    {
      article: '4912',
      name: 'Trodat Printy 4912',
      series: 'printy',
      categorySlug: 'office',
      price: 1190,
      size: '47 x 18 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4912.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4912%0AImpression',
      imageGallery: [],
      inkPad: '6/4912',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'The most popular office stamp. Ideal for company names and addresses with up to 5 lines of text.',
      inStock: true,
      maxLines: 5,
    },
    {
      article: '4913',
      name: 'Trodat Printy 4913',
      series: 'printy',
      categorySlug: 'office',
      price: 1390,
      size: '58 x 22 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4913.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4913%0AImpression',
      imageGallery: [],
      inkPad: '6/4913',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Larger text plate for up to 6 lines. Perfect for detailed company addresses and logos.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '4914',
      name: 'Trodat Printy 4914',
      series: 'printy',
      categorySlug: 'office',
      price: 1590,
      size: '64 x 26 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4914.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4914%0AImpression',
      imageGallery: [],
      inkPad: '6/4914',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Wide format for extended text, accommodating long company names or additional details.',
      inStock: true,
      maxLines: 7,
    },
    {
      article: '4915',
      name: 'Trodat Printy 4915',
      series: 'printy',
      categorySlug: 'office',
      price: 1890,
      size: '70 x 25 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4915.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4915%0AImpression',
      imageGallery: [],
      inkPad: '6/4915',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Extra wide and tall for large addresses, logos, and comprehensive contact details.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '4921',
      name: 'Trodat Printy 4921 Square',
      series: 'printy',
      categorySlug: 'office',
      price: 850,
      size: '12 x 12 mm',
      shape: 'square',
      imageMain: '/images/stamps/4921.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4921%0AImpression',
      imageGallery: ["/images/stamps/4921_gal_1.jpg","/images/stamps/4921_gal_2.jpg","/images/stamps/4921_gal_3.jpg"],
      inkPad: '6/4921',
      featureMci: false,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Miniature square stamp, perfect for inspection marks, initials, or small logos.',
      inStock: true,
      maxLines: 2,
    },
    {
      article: '4922',
      name: 'Trodat Printy 4922 Square',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '20 x 20 mm',
      shape: 'square',
      imageMain: '/images/stamps/4922.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4922%0AImpression',
      imageGallery: ["/images/stamps/4922_gal_1.jpg","/images/stamps/4922_gal_2.jpg","/images/stamps/4922_gal_3.jpg"],
      inkPad: '6/4922',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Compact square design, ideal for monograms or short text blocks.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4923',
      name: 'Trodat Printy 4923 Square',
      series: 'printy',
      categorySlug: 'office',
      price: 1150,
      size: '30 x 30 mm',
      shape: 'square',
      imageMain: '/images/stamps/4923.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4923%0AImpression',
      imageGallery: ["/images/stamps/4923_gal_1.jpg","/images/stamps/4923_gal_2.jpg"],
      inkPad: '6/4923',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Medium square format for more detailed logos or multi-line information.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '4924',
      name: 'Trodat Printy 4924 Square',
      series: 'printy',
      categorySlug: 'office',
      price: 1490,
      size: '40 x 40 mm',
      shape: 'square',
      imageMain: '/images/stamps/4924.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4924%0AImpression',
      imageGallery: ["/images/stamps/4924_gal_1.jpg","/images/stamps/4924_gal_2.jpg"],
      inkPad: '6/4924',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Large square stamp, suitable for complex logos, QR codes, or extensive text.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '46019',
      name: 'Trodat Printy 46019 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 19 mm',
      shape: 'round',
      imageMain: '/images/stamps/46019.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46019%0AImpression',
      imageGallery: ["/images/stamps/46019_gal_1.jpg","/images/stamps/46019_gal_2.jpg"],
      inkPad: '6/46019',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Small circular stamp for inspector numbers, initials, or miniature logos.',
      inStock: true,
      maxLines: 3,
    },
    {
      article: '46025',
      name: 'Trodat Printy 46025 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1050,
      size: 'Ø 25 mm',
      shape: 'round',
      imageMain: '/images/stamps/46025.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46025%0AImpression',
      imageGallery: ["/images/stamps/46025_gal_1.jpg","/images/stamps/46025_gal_2.jpg"],
      inkPad: '6/46025',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Round format for custom graphics, small monograms, and inspection marks.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '46030',
      name: 'Trodat Printy 46030 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1150,
      size: 'Ø 30 mm',
      shape: 'round',
      imageMain: '/images/stamps/46030.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46030%0AImpression',
      imageGallery: ["/images/stamps/46030_gal_1.jpg"],
      inkPad: '6/46030',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Medium circular stamp, great for basic seals, logos, or personalized branding.',
      inStock: true,
      maxLines: 5,
    },
    {
      article: '46040',
      name: 'Trodat Printy 46040 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1250,
      size: 'Ø 40 mm',
      shape: 'round',
      imageMain: '/images/stamps/46040.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46040%0AImpression',
      imageGallery: ["/images/stamps/46040_gal_1.jpg"],
      inkPad: '6/46040',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Classic round seal size, perfectly suited for standard company or notary seals.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '4642',
      name: 'Trodat Printy 4642 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1290,
      size: 'Ø 42 mm',
      shape: 'round',
      imageMain: '/images/stamps/4642.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4642%0AImpression',
      imageGallery: ["/images/stamps/4642_gal_1.jpg","/images/stamps/4642_gal_2.jpg"],
      inkPad: '6/4642',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Circular stamp for official company seals and creative logos, extremely popular worldwide.',
      inStock: true,
      maxLines: 7,
    },
    {
      article: '46045',
      name: 'Trodat Printy 46045 Round',
      series: 'printy',
      categorySlug: 'office',
      price: 1390,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: '/images/stamps/46045.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46045%0AImpression',
      imageGallery: ["/images/stamps/46045_gal_1.jpg"],
      inkPad: '6/46045',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Larger round stamp, ideal for intricate crests, detailed logos, and bilingual seals.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '4926',
      name: 'Trodat Printy 4926',
      series: 'printy',
      categorySlug: 'office',
      price: 1850,
      size: '75 x 38 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4926.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4926%0AImpression',
      imageGallery: [],
      inkPad: '6/4926',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Large rectangular stamp accommodating up to 8 lines. Perfect for extensive tabular information.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '4927',
      name: 'Trodat Printy 4927',
      series: 'printy',
      categorySlug: 'office',
      price: 1650,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4927.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4927%0AImpression',
      imageGallery: [],
      inkPad: '6/4927',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Standard format for prominent addressing or detailed bank and accounting information.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '4928',
      name: 'Trodat Printy 4928',
      series: 'printy',
      categorySlug: 'office',
      price: 1550,
      size: '60 x 33 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4928.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4928%0AImpression',
      imageGallery: [],
      inkPad: '6/4928',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Accommodates long lines of text, commonly used for larger return addresses and instructions.',
      inStock: true,
      maxLines: 7,
    },
    {
      article: '4929',
      name: 'Trodat Printy 4929',
      series: 'printy',
      categorySlug: 'office',
      price: 1450,
      size: '50 x 30 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4929.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4929%0AImpression',
      imageGallery: [],
      inkPad: '6/4929',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Versatile size for custom messages or medium-sized addresses and department names.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5200',
      name: 'Trodat Professional 5200',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2190,
      size: '41 x 24 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5200.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5200%0AImpression',
      imageGallery: [],
      inkPad: '6/50',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Ergonomic, reliable, and durable. The high-quality steel construction guarantees maximum stability.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5203',
      name: 'Trodat Professional 5203',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2450,
      size: '49 x 28 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5203.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5203%0AImpression',
      imageGallery: [],
      inkPad: '6/53',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Robust design for heavy daily use, offering ample space for addresses and basic logos.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5204',
      name: 'Trodat Professional 5204',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2690,
      size: '56 x 26 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5204.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5204%0AImpression',
      imageGallery: [],
      inkPad: '6/56',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Strongest and most reliable heavy-duty stamp for long-term industrial use. Ideal for standard business addresses.',
      inStock: true,
      maxLines: 7,
    },
    {
      article: '5206',
      name: 'Trodat Professional 5206',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2950,
      size: '56 x 33 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5206.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5206%0AImpression',
      imageGallery: [],
      inkPad: '6/56',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Excellent for accommodating detailed texts and prominent graphic elements in heavy use environments.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: '5207',
      name: 'Trodat Professional 5207',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 3250,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5207.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5207%0AImpression',
      imageGallery: [],
      inkPad: '6/5207',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Large surface area for demanding requirements, including accounting layouts or complex graphics.',
      inStock: true,
      maxLines: 9,
    },
    {
      article: '5208',
      name: 'Trodat Professional 5208',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 3600,
      size: '68 x 47 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5208.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5208%0AImpression',
      imageGallery: [],
      inkPad: '6/58',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Extra-large format specifically designed for extensive tables, forms, or multiple signature lines.',
      inStock: true,
      maxLines: 10,
    },
    {
      article: '5211',
      name: 'Trodat Professional 5211',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 4200,
      size: '85 x 55 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5211.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5211%0AImpression',
      imageGallery: [],
      inkPad: '6/511',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'One of the largest heavy-duty stamps, ideal for highly detailed forms, warning labels, or vast text.',
      inStock: true,
      maxLines: 12,
    },
    {
      article: '9411',
      name: 'Trodat Mobile Printy 9411',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 890,
      size: '38 x 14 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/9411.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9411%0AImpression',
      imageGallery: [],
      inkPad: '6/9411',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'The unique one-handed operation pocket stamp. Simple, stable, and clean.',
      inStock: true,
      maxLines: 3,
    },
    {
      article: '9412',
      name: 'Trodat Mobile Printy 9412',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1050,
      size: '47 x 18 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/9412.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9412%0AImpression',
      imageGallery: [],
      inkPad: '6/9412',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Compact travel companion providing enough space for a standard company address or signature.',
      inStock: true,
      maxLines: 5,
    },
    {
      article: '9413',
      name: 'Trodat Mobile Printy 9413',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1250,
      size: '58 x 22 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/9413.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9413%0AImpression',
      imageGallery: [],
      inkPad: '6/9413',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'The largest Mobile Printy size for comprehensive text, logos, or full address blocks on the go.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '9425',
      name: 'Trodat Mobile Printy 9425 Square',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1100,
      size: '25 x 25 mm',
      shape: 'square',
      imageMain: '/images/stamps/9425.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9425%0AImpression',
      imageGallery: [],
      inkPad: '6/9425',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Square pocket stamp layout for logos, initials, and short messages in a highly portable format.',
      inStock: true,
      maxLines: 5,
    },
    {
      article: '4750',
      name: 'Trodat Printy 4750 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 1850,
      size: '41 x 24 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4750.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4750%0AImpression',
      imageGallery: [],
      inkPad: '6/4750',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet","Black/Red"],
      description: 'Popular everyday dater offering two text lines alongside the adjustable date field.',
      inStock: true,
      maxLines: 2,
    },
    {
      article: '4729',
      name: 'Trodat Printy 4729 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 2150,
      size: '50 x 30 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4729.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4729%0AImpression',
      imageGallery: [],
      inkPad: '6/4929',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet","Black/Red"],
      description: 'Mid-sized dater for custom instructions above and below the prominent date band.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4727',
      name: 'Trodat Printy 4727 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 2350,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4727.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4727%0AImpression',
      imageGallery: [],
      inkPad: '6/4927',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet","Black/Red"],
      description: 'Larger dater format suitable for accounting, receiving, and detailed organizational workflows.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5430',
      name: 'Trodat Professional 5430 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: '41 x 24 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5430.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5430%0AImpression',
      imageGallery: [],
      inkPad: '6/50',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet","Black/Red"],
      description: 'Heavy-duty steel-core dater for high-volume environments requiring durability and precision.',
      inStock: true,
      maxLines: 2,
    },
    {
      article: '5440',
      name: 'Trodat Professional 5440 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 3150,
      size: '49 x 28 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5440.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5440%0AImpression',
      imageGallery: [],
      inkPad: '6/53',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet","Black/Red"],
      description: 'Robust and reliable dater with slightly extended space for specialized office workflows.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5460',
      name: 'Trodat Professional 5460 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 3290,
      size: '56 x 33 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5460.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5460%0AImpression',
      imageGallery: [],
      inkPad: '6/56',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet","Black/Red"],
      description: 'Self-inking heavy-duty dater with ample additional text area. Smooth and quiet operation.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '5480',
      name: 'Trodat Professional 5480 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 4500,
      size: '68 x 47 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5480.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5480%0AImpression',
      imageGallery: [],
      inkPad: '6/58',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet","Black/Red"],
      description: 'Extensive format dater suitable for large tables, comprehensive status updates, and sign-offs.',
      inStock: true,
      maxLines: 8,
    },
    {
      article: 'Ideal Seal',
      name: 'Trodat Ideal Seal',
      series: 'ideal',
      categorySlug: 'embossers',
      price: 4500,
      size: 'Ø 41 mm',
      shape: 'round',
      imageMain: '/images/stamps/Ideal Seal.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=Ideal%0AShadow',
      imageGallery: [],
      inkPad: 'None',
      featureMci: false,
      featureEco: false,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["None (Embossing)"],
      description: 'High-quality embossing press for certificates, stationary, and official documents. Leaves a crisp impression.',
      inStock: true,
      maxLines: undefined,
    },
    {
      article: '4810',
      name: 'Trodat Printy 4810 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 850,
      size: 'Date height 3.8 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4810.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4810%0AImpression',
      imageGallery: [],
      inkPad: '6/4910',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Compact dater with 3.8 mm date height. Standard format: DD.MM.YYYY.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '4820',
      name: 'Trodat Printy 4820 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 950,
      size: 'Date height 4 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4820.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4820%0AImpression',
      imageGallery: [],
      inkPad: '6/4911',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Dater with 4 mm date height. Ideal for banking and standard document marking.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '4836',
      name: 'Trodat Printy 4836 Numerator',
      series: 'printy',
      categorySlug: 'daters',
      price: 950,
      size: '3.8 mm (6 digits)',
      shape: 'rectangle',
      imageMain: '/images/stamps/4836.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4836%0AImpression',
      imageGallery: [],
      inkPad: '6/4910',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: '6-digit numbering stamp with 3.8 mm character height.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '4846',
      name: 'Trodat Printy 4846 Numerator',
      series: 'printy',
      categorySlug: 'daters',
      price: 1050,
      size: '4.0 mm (6 digits)',
      shape: 'rectangle',
      imageMain: '/images/stamps/4846.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4846%0AImpression',
      imageGallery: [],
      inkPad: '6/4911',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: '6-digit numerator with additional special characters. Character height 4 mm.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '48313',
      name: 'Trodat Printy 48313 Numerator',
      series: 'printy',
      categorySlug: 'daters',
      price: 1850,
      size: '3.8 mm (13 digits)',
      shape: 'rectangle',
      imageMain: '/images/stamps/48313.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=48313%0AImpression',
      imageGallery: [],
      inkPad: '6/4817',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Wide 13-digit numbering stamp. Perfect for long tracking numbers. Character height 3.8 mm.',
      inStock: true,
      maxLines: 1,
    },
    {
      article: '9342',
      name: 'Trodat Micro Printy 9342',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1250,
      size: 'Ø 42 mm',
      shape: 'round',
      imageMain: '/images/stamps/9342.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9342%0AImpression',
      imageGallery: [],
      inkPad: 'Built-in',
      featureMci: false,
      featureEco: false,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Simple, light, and compact round pocket stamp. Features an adhesive layer for easy mounting.',
      inStock: true,
      maxLines: 6,
    },
    {
      article: '9511',
      name: 'Trodat Pocket Printy 9511',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 950,
      size: '38 x 14 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/9511.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9511%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Extremely compact and perfectly designed pocket stamp with slide mechanism.',
      inStock: true,
      maxLines: 3,
    },
    {
      article: '7011',
      name: 'Trodat Stamp Ink 7011 (28ml)',
      series: 'accessories',
      categorySlug: 'accessories',
      price: 350,
      size: '28 ml',
      shape: 'bottle',
      imageMain: '/images/stamps/7011.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=7011%0AInk',
      imageGallery: [],
      inkPad: 'None',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Water-based stamp ink suitable for all rubber and polymer text plates. Environmentally friendly.',
      inStock: true,
      maxLines: 0,
    },
    {
      article: '9052',
      name: 'Trodat Stamp Pad 9052',
      series: 'accessories',
      categorySlug: 'accessories',
      price: 550,
      size: '110 x 70 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/9052.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9052%0APad',
      imageGallery: [],
      inkPad: 'None',
      featureMci: false,
      featureEco: true,
      featurePositioning: false,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet","Un-inked"],
      description: 'Desktop stamp pad with new modern design. Guaranteed thousands of clean impressions.',
      inStock: true,
      maxLines: 0,
    },
    {
      article: '44045',
      name: 'Trodat Printy 44045',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '45 x 30 mm',
      shape: 'oval',
      imageMain: '/images/stamps/44045.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=44045%0AImpression',
      imageGallery: [],
      inkPad: '6/44045',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 44045. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '44055',
      name: 'Trodat Printy 44055',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '55 x 35 mm',
      shape: 'oval',
      imageMain: '/images/stamps/44055.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=44055%0AImpression',
      imageGallery: [],
      inkPad: '6/44055',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 44055. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4600',
      name: 'Trodat Ideal 4600',
      series: 'ideal',
      categorySlug: 'embossers',
      price: 950,
      size: 'Standard size',
      shape: 'rectangle',
      imageMain: '/images/stamps/4600.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4600%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Ideal model 4600. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '46042',
      name: 'Trodat Ideal 46042',
      series: 'ideal',
      categorySlug: 'embossers',
      price: 950,
      size: '42 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/46042.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46042%0AImpression',
      imageGallery: ["/images/stamps/46042_gal_1.jpg","/images/stamps/46042_gal_2.jpg","/images/stamps/46042_gal_3.jpg","/images/stamps/46042_gal_4.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Ideal model 46042. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '46050',
      name: 'Trodat Printy 46050',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 50 mm',
      shape: 'round',
      imageMain: '/images/stamps/46050.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46050%0AImpression',
      imageGallery: ["/images/stamps/46050_gal_1.jpg"],
      inkPad: '6/46050',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 46050. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '46119',
      name: 'Trodat Professional 46119 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Ø 19 mm',
      shape: 'round',
      imageMain: '/images/stamps/46119.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46119%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 46119. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4612',
      name: 'Trodat Printy 4612',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 12 mm',
      shape: 'round',
      imageMain: '/images/stamps/4612.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4612%0AImpression',
      imageGallery: [],
      inkPad: '6/4612',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4612. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '46130',
      name: 'Trodat Printy 46130',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 30 mm',
      shape: 'round',
      imageMain: '/images/stamps/46130.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46130%0AImpression',
      imageGallery: ["/images/stamps/46130_gal_1.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 46130. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '46140',
      name: 'Trodat Printy 46140',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 40 mm',
      shape: 'round',
      imageMain: '/images/stamps/46140.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46140%0AImpression',
      imageGallery: ["/images/stamps/46140_gal_1.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 46140. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '46145',
      name: 'Trodat Printy 46145',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: '/images/stamps/46145.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=46145%0AImpression',
      imageGallery: ["/images/stamps/46145_gal_1.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 46145. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4630',
      name: 'Trodat Printy 4630',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 30 mm',
      shape: 'round',
      imageMain: '/images/stamps/4630.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4630%0AImpression',
      imageGallery: ["/images/stamps/4630_gal_1.jpg","/images/stamps/4630_gal_2.jpg"],
      inkPad: '6/4630',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4630. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4645',
      name: 'Trodat Printy 4645',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: '/images/stamps/4645.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4645%0AImpression',
      imageGallery: ["/images/stamps/4645_gal_1.jpg"],
      inkPad: '6/4645',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4645. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4724',
      name: 'Trodat Printy 4724',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '40 x 40 mm',
      shape: 'square',
      imageMain: '/images/stamps/4724.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4724%0AImpression',
      imageGallery: ["/images/stamps/4724_gal_1.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4724. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4726',
      name: 'Trodat Printy 4726 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 1150,
      size: '75 x 38 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4726.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4726%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4726. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4755',
      name: 'Trodat Mobile Printy 4755',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1050,
      size: '41 x 24 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4755.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4755%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Mobile Printy model 4755. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4813',
      name: 'Trodat Printy 4813 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 1150,
      size: '26 x 9 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4813.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4813%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4813. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4817',
      name: 'Trodat Printy 4817',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '47 x 9 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4817.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4817%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4817. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4822',
      name: 'Trodat Printy 4822 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 1150,
      size: '25 x 5 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4822.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4822%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4822. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4850',
      name: 'Trodat Printy 4850 Dater',
      series: 'printy',
      categorySlug: 'daters',
      price: 1150,
      size: '25 x 5 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4850.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4850%0AImpression',
      imageGallery: [],
      inkPad: '6/4850',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4850. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4908',
      name: 'Trodat Printy 4908',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '15 x 7 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4908.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4908%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4908. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4916',
      name: 'Trodat Printy 4916',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '70 x 10 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4916.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4916%0AImpression',
      imageGallery: [],
      inkPad: '6/4916',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4916. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4917',
      name: 'Trodat Printy 4917',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '50 x 10 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4917.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4917%0AImpression',
      imageGallery: [],
      inkPad: '6/4817',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4917. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4918',
      name: 'Trodat Printy 4918',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '75 x 15 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4918.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4918%0AImpression',
      imageGallery: [],
      inkPad: '6/4926',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4918. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4925',
      name: 'Trodat Printy 4925',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '82 x 25 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4925.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4925%0AImpression',
      imageGallery: [],
      inkPad: '6/4925',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4925. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4931',
      name: 'Trodat Printy 4931',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '70 x 30 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4931.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4931%0AImpression',
      imageGallery: [],
      inkPad: '6/4931',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4931. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4933',
      name: 'Trodat Printy 4933',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '25 x 25 mm',
      shape: 'square',
      imageMain: '/images/stamps/4933.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4933%0AImpression',
      imageGallery: [],
      inkPad: '6/4933',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4933. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4940',
      name: 'Trodat Professional 4940 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Standard size',
      shape: 'rectangle',
      imageMain: '/images/stamps/4940.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4940%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 4940. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '4941',
      name: 'Trodat Printy 4941',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: '41 x 24 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/4941.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=4941%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 4941. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5030',
      name: 'Trodat Professional 5030 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: '/images/stamps/5030.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5030%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5030. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5117',
      name: 'Trodat Professional 5117 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Standard size',
      shape: 'rectangle',
      imageMain: '/images/stamps/5117.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5117%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5117. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '52040',
      name: 'Trodat Professional 52040',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: 'Ø 40 mm',
      shape: 'round',
      imageMain: '/images/stamps/52040.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=52040%0AImpression',
      imageGallery: ["/images/stamps/52040_gal_1.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 52040. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '52045',
      name: 'Trodat Professional 52045',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: '/images/stamps/52045.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=52045%0AImpression',
      imageGallery: ["/images/stamps/52045_gal_1.jpg","/images/stamps/52045_gal_2.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 52045. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5205',
      name: 'Trodat Professional 5205',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: '68 x 24 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5205.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5205%0AImpression',
      imageGallery: [],
      inkPad: '6/55',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5205. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5212',
      name: 'Trodat Professional 5212 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: '116 x 70 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5212.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5212%0AImpression',
      imageGallery: [],
      inkPad: '6/512',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5212. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '52140',
      name: 'Trodat Professional 52140 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Standard size',
      shape: 'rectangle',
      imageMain: '/images/stamps/52140.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=52140%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 52140. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5215',
      name: 'Trodat Professional 5215 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Standard size',
      shape: 'rectangle',
      imageMain: '/images/stamps/5215.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5215%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5215. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5253',
      name: 'Trodat Professional 5253 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: '49 x 28 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5253.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5253%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5253. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5274',
      name: 'Trodat Professional 5274',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5274.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5274%0AImpression',
      imageGallery: [],
      inkPad: '6/58',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5274. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '54045',
      name: 'Trodat Professional 54045 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: '/images/stamps/54045.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=54045%0AImpression',
      imageGallery: ["/images/stamps/54045_gal_1.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 54045. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '54110',
      name: 'Trodat Professional 54110',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: '85 x 55 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/54110.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=54110%0AImpression',
      imageGallery: [],
      inkPad: '6/511',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 54110. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '54140',
      name: 'Trodat Professional 54140',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: 'Ø 40 mm',
      shape: 'round',
      imageMain: '/images/stamps/54140.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=54140%0AImpression',
      imageGallery: ["/images/stamps/54140_gal_1.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 54140. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5415',
      name: 'Trodat Professional 5415 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: '/images/stamps/5415.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5415%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5415. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5435',
      name: 'Trodat Professional 5435 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Ø 35 mm',
      shape: 'round',
      imageMain: '/images/stamps/5435.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5435%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5435. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '54510',
      name: 'Trodat Professional 54510',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: '85 x 55 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/54510.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=54510%0AImpression',
      imageGallery: ["/images/stamps/54510_gal_1.jpg","/images/stamps/54510_gal_2.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 54510. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5465',
      name: 'Trodat Professional 5465 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Ø 45 mm',
      shape: 'round',
      imageMain: '/images/stamps/5465.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5465%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5465. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5466',
      name: 'Trodat Professional 5466 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: '56 x 33 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5466.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5466%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5466. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5470',
      name: 'Trodat Professional 5470 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5470.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5470%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5470. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5474',
      name: 'Trodat Professional 5474',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: '60 x 40 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5474.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5474%0AImpression',
      imageGallery: [],
      inkPad: '6/58',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5474. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5485',
      name: 'Trodat Professional 5485',
      series: 'professional',
      categorySlug: 'heavy-duty',
      price: 2500,
      size: '68 x 47 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5485.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5485%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5485. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5546',
      name: 'Trodat Professional 5546 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Height 4 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5546.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5546%0AImpression',
      imageGallery: [],
      inkPad: '6/50',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5546. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '55510',
      name: 'Trodat Professional 55510 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Height 5 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/55510.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=55510%0AImpression',
      imageGallery: [],
      inkPad: '6/56',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 55510. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5558',
      name: 'Trodat Professional 5558 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: 'Height 5 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5558.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5558%0AImpression',
      imageGallery: [],
      inkPad: '6/56',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5558. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '5756',
      name: 'Trodat Professional 5756 Dater',
      series: 'professional',
      categorySlug: 'daters',
      price: 2850,
      size: '5.5 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/5756.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=5756%0AImpression',
      imageGallery: ["/images/stamps/5756_gal_1.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Professional model 5756. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '9001',
      name: 'Trodat Printy 9001',
      series: 'printy',
      categorySlug: 'office',
      price: 950,
      size: 'Standard size',
      shape: 'rectangle',
      imageMain: '/images/stamps/9001.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9001%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Printy model 9001. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '9051',
      name: 'Trodat Accessories 9051',
      series: 'accessories',
      categorySlug: 'accessories',
      price: 450,
      size: '90 x 50 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/9051.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9051%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black"],
      description: 'Trodat Accessories model 9051. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 0,
    },
    {
      article: '9053',
      name: 'Trodat Accessories 9053',
      series: 'accessories',
      categorySlug: 'accessories',
      price: 450,
      size: '160 x 90 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/9053.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9053%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black"],
      description: 'Trodat Accessories model 9053. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 0,
    },
    {
      article: '9430',
      name: 'Trodat Mobile Printy 9430',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1050,
      size: 'Ø 30 mm',
      shape: 'round',
      imageMain: '/images/stamps/9430.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9430%0AImpression',
      imageGallery: ["/images/stamps/9430_gal_1.jpg","/images/stamps/9430_gal_2.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Mobile Printy model 9430. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '9440',
      name: 'Trodat Mobile Printy 9440',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1050,
      size: 'Ø 40 mm',
      shape: 'round',
      imageMain: '/images/stamps/9440.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9440%0AImpression',
      imageGallery: ["/images/stamps/9440_gal_1.jpg","/images/stamps/9440_gal_2.jpg"],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Mobile Printy model 9440. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '9500',
      name: 'Trodat Ideal 9500',
      series: 'ideal',
      categorySlug: 'embossers',
      price: 950,
      size: 'Standard size',
      shape: 'rectangle',
      imageMain: '/images/stamps/9500.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9500%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Ideal model 9500. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '9512',
      name: 'Trodat Pocket Printy 9512',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1050,
      size: '47 x 18 mm',
      shape: 'rectangle',
      imageMain: '/images/stamps/9512.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9512%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Pocket Printy model 9512. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    },
    {
      article: '9515',
      name: 'Trodat Pocket Printy 9515',
      series: 'mobile',
      categorySlug: 'pocket',
      price: 1050,
      size: 'Ø 15 mm',
      shape: 'round',
      imageMain: '/images/stamps/9515.jpg',
      imageImpression: 'https://placehold.co/200x200/000000/ffffff?text=9515%0AImpression',
      imageGallery: [],
      inkPad: 'None',
      featureMci: true,
      featureEco: true,
      featurePositioning: true,
      colors: ["Black"],
      inkColors: ["Black","Blue","Red","Green","Violet"],
      description: 'Trodat Pocket Printy model 9515. High-quality stamp conforming to official catalog specifications.',
      inStock: true,
      maxLines: 4,
    }
  ];

  for (const stamp of stamps) {
    const { categorySlug, ...data } = stamp;
    await prisma.stamp.upsert({
      where: { article: data.article },
      update: { ...data, categoryId: categoryMap[categorySlug] },
      create: { ...data, categoryId: categoryMap[categorySlug] },
    });
  }
  console.log(`  ✅ ${stamps.length} stamps seeded`);

  // ── Create Demo Admin User ───────────────
  const hashedPassword = await bcrypt.hash('Admin123!', 12);
  await prisma.user.upsert({
    where: { email: 'admin@trodat-shop.com' },
    update: {},
    create: {
      name: 'Admin',
      email: 'admin@trodat-shop.com',
      phone: '+1234567890',
      password: hashedPassword,
      role: 'ADMIN',
    },
  });
  console.log('  ✅ Demo admin user seeded (admin@trodat-shop.com / Admin123!)');

  console.log('🎉 Seeding complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
